"use client";
import {ChangeEvent,useMemo,useState} from "react";
type Row={id:number;name:string;amount:number}; type Field={id:number;name:string;value:string};
const fmt=(n:number,currency:string)=>`${currency.trim()||"UGX"} ${n.toLocaleString("en-UG",{minimumFractionDigits:0,maximumFractionDigits:2})}`;
const currencyName=(currency:string)=>({"UGX":"Uganda Shillings","USH":"Uganda Shillings","KSH":"Kenya Shillings","KES":"Kenya Shillings","USD":"US Dollars","$":"US Dollars","EUR":"Euros","€":"Euros","GBP":"Pounds Sterling","£":"Pounds Sterling"}[currency.trim().toUpperCase()]||currency.trim()||"Currency Units");
const words=(n:number,currency:string)=>{const a=["","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen","Seventeen","Eighteen","Nineteen"],b=["","","Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"];const u=(x:number):string=>x<20?a[x]:x<100?b[Math.floor(x/10)]+(x%10?` ${a[x%10]}`:""):`${a[Math.floor(x/100)]} Hundred${x%100?` ${u(x%100)}`:""}`;let x=Math.max(0,Math.floor(n));if(!x)return`Zero ${currencyName(currency)} Only`;const p:string[]=[];for(const [s,l] of [[1000000000,"Billion"],[1000000,"Million"],[1000,"Thousand"]] as [number,string][]){const c=Math.floor(x/s);if(c){p.push(`${u(c)} ${l}`);x%=s}}if(x)p.push(u(x));return `${p.join(" ")} ${currencyName(currency)} Only`};
export default function Home(){
 const month=new Intl.DateTimeFormat("en",{month:"long",year:"numeric"}).format(new Date());
 const [logo,setLogo]=useState("");const [company,setCompany]=useState({name:"",address:"",city:"",country:"Uganda",currency:"UGX",month});const [employee,setEmployee]=useState({name:"",id:"",period:month,paid:"",lop:"0",date:new Date().toISOString().slice(0,10)});const [fields,setFields]=useState<Field[]>([]);const [earnings,setEarnings]=useState<Row[]>([{id:1,name:"Basic",amount:0},{id:2,name:"House Rent Allowance",amount:0}]);const [deductions,setDeductions]=useState<Row[]>([{id:1,name:"Income Tax",amount:0},{id:2,name:"Provident Fund",amount:0}]);const [preview,setPreview]=useState(false);const [error,setError]=useState("");
 const gross=useMemo(()=>earnings.reduce((s,r)=>s+Number(r.amount||0),0),[earnings]);const deducted=useMemo(()=>deductions.reduce((s,r)=>s+Number(r.amount||0),0),[deductions]);const net=gross-deducted;
 const change=(type:"earnings"|"deductions",id:number,key:"name"|"amount",value:string)=>{const set=type==="earnings"?setEarnings:setDeductions;set(rows=>rows.map(r=>r.id===id?{...r,[key]:key==="amount"?Math.max(0,Number(value)):value}:r))};
 const add=(type:"earnings"|"deductions")=>{const set=type==="earnings"?setEarnings:setDeductions;const rows=type==="earnings"?earnings:deductions;set([...rows,{id:Date.now(),name:"",amount:0}])};
 const remove=(type:"earnings"|"deductions",id:number)=>{const set=type==="earnings"?setEarnings:setDeductions;set(rows=>rows.filter(r=>r.id!==id))};
 const upload=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(f.size>1048576){setError("Logo must be 1MB or smaller.");return}const r=new FileReader();r.onload=()=>setLogo(String(r.result));r.readAsDataURL(f)};
 const [pdfBusy,setPdfBusy]=useState(false);
 const downloadPdf=async()=>{const sheet=document.querySelector<HTMLElement>(".sheet");if(!sheet)return;setPdfBusy(true);try{const html2pdf=(await import("html2pdf.js")).default;const filename=`${employee.name||"employee"}-${employee.period||"payslip"}`.replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase();await html2pdf().set({margin:0,filename:`${filename}.pdf`,image:{type:"jpeg",quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:"mm",format:"a4",orientation:"portrait"}}).from(sheet).save()}catch{alert("The PDF could not be downloaded. Please try again.")}finally{setPdfBusy(false)}};
 const generate=()=>{if(!company.name.trim()||!employee.name.trim()){setError("Please enter the company name and employee name.");scrollTo({top:0,behavior:"smooth"});return}setError("");setCompany(current=>({...current,month:employee.period||current.month}));setPreview(true);scrollTo(0,0)};
 const Slip=()=> <section className="sheet"><header className="slip-head"><div className="slip-brand">{logo?<img src={logo} alt="Company logo"/>:<span>LOGO</span>}<div><h2>{company.name}</h2><p>{company.address}</p><p>{[company.city,company.country].filter(Boolean).join(", ")}</p></div></div><div><b>Payslip For the Month</b><strong>{company.month}</strong></div></header><h3>EMPLOYEE PAY SUMMARY</h3><div className="summary"><dl><div><dt>Employee Name</dt><dd>{employee.name}</dd></div><div><dt>Employee ID</dt><dd>{employee.id||"—"}</dd></div>{fields.filter(f=>f.name).map(f=><div key={f.id}><dt>{f.name}</dt><dd>{f.value||"—"}</dd></div>)}</dl><dl><div><dt>Pay Period</dt><dd>{employee.period}</dd></div><div><dt>Pay Date</dt><dd>{employee.date}</dd></div><div><dt>Paid Days</dt><dd>{employee.paid||"—"}</dd></div><div><dt>LOP Days</dt><dd>{employee.lop}</dd></div></dl><aside><span>Employee Net Pay</span><b>{fmt(net,company.currency)}</b><small>Paid Days: {employee.paid||"—"}</small></aside></div><div className="tables">{[["EARNINGS",earnings,gross],["DEDUCTIONS",deductions,deducted]].map(([title,rows,total])=><table key={String(title)}><thead><tr><th>{String(title)}</th><th>AMOUNT</th></tr></thead><tbody>{(rows as Row[]).filter(r=>r.name).map(r=><tr key={r.id}><td>{r.name}</td><td>{fmt(r.amount,company.currency)}</td></tr>)}</tbody><tfoot><tr><th>{title==="EARNINGS"?"Gross Earnings":"Total Deductions"}</th><th>{fmt(Number(total),company.currency)}</th></tr></tfoot></table>)}</div><div className="slip-total"><div><b>TOTAL NET PAYABLE</b><span>Gross Earnings - Total Deductions</span></div><strong>{fmt(net,company.currency)}</strong></div><p className="amount">Amount in words: <b>{words(net,company.currency)}</b></p><p className="note">This is a computer-generated payslip and does not require a signature.</p></section>;
 if(preview)return <main className="preview"><div className="preview-actions no-print"><button className="secondary" onClick={()=>setPreview(false)}>← Go Back</button><div className="preview-action-group"><button className="secondary" onClick={()=>print()}>Print</button><button className="primary" disabled={pdfBusy} onClick={downloadPdf}>{pdfBusy?"Preparing PDF…":"Download PDF"}</button></div></div><Slip/></main>;
 return <main><section className="hero"><div className="mark">PS</div><h1>Free Payslip Generator</h1><p>Create professional payslips for your employees instantly. Easy to use, customisable, and private.</p></section><section className="card">{error&&<div className="error">{error}</div>}<div className="company"><label className="upload"><input type="file" accept="image/png,image/jpeg" onChange={upload}/><span>{logo?<img src={logo} alt="Uploaded logo"/>:"Upload"}</span><b>Upload Logo</b><small>240 × 240 pixels, maximum 1MB</small></label><div className="company-fields"><label>Payslip For the Month<input value={employee.period} onChange={e=>setEmployee({...employee,period:e.target.value})}/></label><label>Currency symbol or code<input list="currency-options" aria-label="Currency symbol or code" placeholder="UGX, $, €, KSh…" value={company.currency} onChange={e=>setCompany({...company,currency:e.target.value})}/><datalist id="currency-options"><option value="UGX"/><option value="KSh"/><option value="USD"/><option value="$"/><option value="EUR"/><option value="€"/><option value="GBP"/><option value="£"/><option value="RWF"/><option value="Rs."/></datalist></label><input className="wide" aria-label="Company name" placeholder="Company Name*" value={company.name} onChange={e=>setCompany({...company,name:e.target.value})}/><input className="wide" aria-label="Company address" placeholder="Company Address" value={company.address} onChange={e=>setCompany({...company,address:e.target.value})}/><input aria-label="City and pincode" placeholder="City, Pincode" value={company.city} onChange={e=>setCompany({...company,city:e.target.value})}/><input aria-label="Country" placeholder="Country" value={company.country} onChange={e=>setCompany({...company,country:e.target.value})}/></div></div>
 <section className="section"><h2>Employee Pay Summary <em>*</em></h2><div className="employee">{[["Employee Name","name","Eg: Meera Krishnan"],["Employee ID","id","Eg: 1234"],["Pay Period","period",month],["Paid Days","paid","22"],["Loss of Pay Days","lop","0"],["Pay Date","date",""]].map(([label,key,placeholder])=><label key={key}>{label}<input type={["paid","lop"].includes(key)?"number":key==="date"?"date":"text"} placeholder={placeholder} value={employee[key as keyof typeof employee]} onChange={e=>setEmployee({...employee,[key]:e.target.value})}/></label>)}</div>{fields.map(f=><div className="custom" key={f.id}><input placeholder="Name" value={f.name} onChange={e=>setFields(fields.map(x=>x.id===f.id?{...x,name:e.target.value}:x))}/><input placeholder="Value" value={f.value} onChange={e=>setFields(fields.map(x=>x.id===f.id?{...x,value:e.target.value}:x))}/><button onClick={()=>setFields(fields.filter(x=>x.id!==f.id))}>×</button></div>)}<button className="link" onClick={()=>setFields([...fields,{id:Date.now(),name:"",value:""}])}>＋ Add another field</button></section>
 <section className="section"><h2>Income Details <em>*</em></h2><div className="income">{(["earnings","deductions"] as const).map(type=>{const rows=type==="earnings"?earnings:deductions;const total=type==="earnings"?gross:deducted;return <div className="money" key={type}><div className="money-head"><b>{type}</b><b>Amount</b></div>{rows.map(r=><div className="money-row" key={r.id}><input aria-label={`${type} name`} value={r.name} onChange={e=>change(type,r.id,"name",e.target.value)}/><input aria-label={`${r.name} amount`} type="number" min="0" value={r.amount} onChange={e=>change(type,r.id,"amount",e.target.value)}/><button onClick={()=>remove(type,r.id)}>×</button></div>)}<button className="link add" onClick={()=>add(type)}>＋ Add {type}</button><div className="subtotal"><b>{type==="earnings"?"Gross Earnings":"Total Deductions"}</b><strong>{fmt(total,company.currency)}</strong></div></div>})}</div></section><div className="net"><div><b>Total Net Payable</b><small>Gross Earnings - Total Deductions</small></div><strong>{fmt(net,company.currency)}</strong></div><p className="words"><b>Amount in words:</b> {words(net,company.currency)}</p><div className="actions"><button className="primary" onClick={generate}>Generate Payslip</button><button className="secondary" onClick={()=>location.reload()}>Reset</button></div></section>
 <section className="info"><h2>Generate a payslip in four simple steps</h2><div>{["Enter company details","Add employee information","List earnings and deductions","Preview and download"].map((t,i)=><article key={t}><span>0{i+1}</span><b>{t}</b></article>)}</div></section><footer><b>PS · Free Payslip Generator</b><small>Your information stays in your browser and is not saved by this website.</small></footer></main>
}
